apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: prod
  REDIS_HOST: redis-cache-uxe7sb.serverless.aps1.cache.amazonaws.com
  REDIS_PORT: "6379"

