pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "rajreeshu/ruber-backend-aws"
        ECR_URL = "072510400111.dkr.ecr.ap-south-1.amazonaws.com/ruber-backend"
    }

    // tools {
    //     maven 'Maven-3.9.12'   // Configure in Jenkins Global Tools
    // }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/rajreeshu/Ruber-UberClone-System-Design.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('BackEnd/Uber'){
                    sh 'mvn clean package -DskipTests'
                }
                sh 'whoami'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('BackEnd/Uber') {
                    sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    sh """
                    aws ecr get-login-password --region ap-south-1 | \
                    docker login --username AWS --password-stdin ${ECR_URL}

                    docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${ECR_URL}:${BUILD_NUMBER}
                    docker push ${ECR_URL}:${BUILD_NUMBER}
                    """
                }
            }
        }

        // stage('Push Docker Image') {
        //     steps {
        //         withCredentials([usernamePassword(
        //             credentialsId: 'dockerhub-creds',
        //             usernameVariable: 'DOCKER_USER',
        //             passwordVariable: 'DOCKER_PASS'
        //         )]) {
        //             sh """
        //                 echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        //                 docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
        //             """
        //         }
        //     }
        // }
    }

    post {
        success {
            echo "Pipeline executed successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}