spring.datasource.url=jdbc:mysql://127.0.0.1:3306/uber_system
spring.datasource.username=uber_application
spring.datasource.password=uber123

########## MAP Properties ##########

# resolution => 7 ~ 5.17km^2 || 8 ~ 1km^2 || 9 ~ 0.1km^2
map.h3.resolution=8

########## Redis Properties ##########
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

