########## Postgres Properties ##########
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ruber_app
spring.datasource.username=postgres
spring.datasource.password=password

########## Redis Properties ##########
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

server.port=8080

