########## MAP Properties ##########
# resolution => 7 ~ 5.17km^2 || 8 ~ 1km^2 || 9 ~ 0.1km^2 (1 H3 tile will contain how much area)
map.h3.resolution=8

########## Redis Properties ##########
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379